spring.application.name=package-service
server.port=8080

spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.url=jdbc:postgresql://localhost:5432/packagedb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql

# Axon Configuration
axon.axonserver.servers=axon-server:8124
axon.axonserver.ssl-enabled=false
axon.commandgateway.spring-autoconfiguration.enabled=true