# Application
spring.application.name=tracking-service
server.port=8083
debug=true

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres-db:5432/trackingdb
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate

# Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# Axon (CQRS)
axon.axonserver.servers=axon-server:8124
axon.eventhandling.processors.trackingProcessor.mode=tracking
axon.serializer.events=jackson