spring.application.name=trackingService
server.port=8084

spring.datasource.username=postgres
spring.datasource.password=root
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.datasource.url=jdbc:postgresql://localhost:5432/trackingdb
spring.jpa.hibernate.ddl-auto=validate

axon.eventhandling.processors.trackingProcessor.mode: tracking