spring.application.name=location-service
server.port=8081

spring.data.mongodb.uri=mongodb://mongodb:27017/locationdb
spring.data.mongodb.database=locationdb
spring.data.mongodb.auto-index-creation=true
debug=true

